apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "lion.db.fullname" . }}
type: Opaque
data:
  POSTGRES_DB: bGlvbmZvcnVt # lionforum
  POSTGRES_USER: bGlvbg== # lion
  POSTGRES_PASSWORD: dGlnZXI= # tiger
  POSTGRES_PORT: NTQzMg==
